---
- name: Create tmp path for Dockerbuild
  ansible.builtin.file:
    path: "{{ tmp_path }}/fah"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Move Dockerfile build context path
  ansible.builtin.copy:
    src: "Dockerfile"
    dest: "{{ tmp_path }}/fah/Dockerfile"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rwx,g=rx,o=rx

- name: Move config.xml to context path
  ansible.builtin.template:
    src: config.xml.j2
    dest: "{{ tmp_path }}/fah/config.xml"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rwx,g=rx,o=rx

- name: Build foldingathome image
  community.docker.docker_image:
    source: build
    build:
      args: 
        FAHCLIENT_UID: "{{ ansible_facts['user_uid'] }}"
      path: "{{ tmp_path }}/fah/"
      cache_from: foldingathome:latest
    name: foldingathome
    tag: latest

- name: Create tmp path for Dockerbuild
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/ContainerData/foldingathome"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy foldingathome container
  community.docker.docker_container:
    name: foldingathome
    image: foldingathome
    volumes:
      - "{{ ansible_facts['user_dir'] }}/ContainerData/foldingathome:/fahclient"
