---
# - name: Check if sshaws is installed
#   ansible.builtin.stat:
#     path: "{{ sshaws_installation_path }}/sshaws"
#   register: sshaws

- name: Download .deb
  ansible.builtin.get_url:
    url: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb"
    dest: "{{ tmp_path }}/session-manager-plugin.deb"
    owner: "{{ caller_user.stdout }}"
    group: "{{ caller_group.stdout }}"
    mode: u=rw,g=r,o=r

- name: Install .deb file
  ansible.builtin.apt:
    deb: "{{ tmp_path }}/session-manager-plugin.deb"
  become: True
