---
- name: Get aws_ssm_plugin current version
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      session-manager-plugin --version
  register: aws_ssm_plugin_current_version
  changed_when: false
  failed_when: false

- debug:
    msg: "Version -> {{ version }}"
- debug:
    msg: "current version -> {{ aws_ssm_plugin_current_version.stdout }}"

- name: Install aws_ssm_plugin if version outdated
  ansible.builtin.include_tasks: install.yml
  when: aws_ssm_plugin_current_version.rc != 0 or aws_ssm_plugin_current_version.stdout != version
