---
- name: Install aws-cli
  ansible.builtin.snap:
    name: aws-cli
    state: present
    classic: true
  become: true

- name: Get aws_ssm_plugin current version
  ansible.builtin.command: session-manager-plugin --version
  register: ssm_plugin_current_version
  changed_when: false
  failed_when: false
  when: install_ssm_plugin

- name: Install aws_ssm_plugin
  ansible.builtin.include_tasks: install_ssm_plugin.yml
  when: |
    install_ssm_plugin and (
      ssm_plugin_current_version is failed or
      ssm_plugin_current_version.stdout != ssm_plugin_version|replace("+", ".")
    )
