---
- name: Install in macOS
  community.general.homebrew:
    name: awscli
    state: latest  
  when: ansible_distribution == "MacOSX"

- name: Install in Ubuntu
  community.general.snap:
    name: aws-cli
    state: present
    classic: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Copy bashrc config
  ansible.builtin.copy:
    src: "awsprofile.bash"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/awsprofile.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r

