---
- name: Ensure .bashrc.d directory exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.bashrc.d'
    state: directory
    mode: '0755'

- name: Copy .bashrc config
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: "{{ caller_user.stdout }}"
    group: "{{ caller_group.stdout }}"
    mode: u=rw,g=r,o=r
  loop:
    - src: bashrc
      dest: '{{ ansible_env.HOME }}/.bashrc'
    - src: bashrc.d/
      dest: '{{ ansible_env.HOME }}/.bashrc.d'
