---
- name: Install microk8s from snap
  ansible.builtin.snap:
    name: microk8s
    state: present
  become: true

- name: Add user to microk8s group.
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: microk8s
    append: true
    state: present
  become: true

- name: Create .kube folder
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.kube"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    state: directory

- name: Copy .bashrc config
  ansible.builtin.copy:
    src: aliases_microk8s.bash
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/aliases_microk8s.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
