---
- name: Install microk8s
  community.general.snap:
    name: microk8s

- name: Add user to microk8s group.
  ansible.builtin.user:
    name: "{{ local_user }}"
    groups: microk8s
    append: true
    state: present
  become: true

- name: Install wrappers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ local_user }}"
    group: "{{ local_group }}"
    mode: u=xrw,g=r,o=r
  become: true
  loop:
    - helm3
    - kubectl
