- name: Update apt database
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 28800 # 8 hours * 3600 = 28800 seconds
  become: true
  changed_when: false

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: full
  become: true

- name: Install apt packages
  ansible.builtin.apt:
    name: '{{ apt_packages_list }}'

    state: present
  become: true
