---
- name: Install Kubectl
  ansible.builtin.snap:
    name: kubectl
    state: present
    classic: true
  become: true

- name:
  ansible.builtin.include_tasks: kubectx.yaml
  when: kubectl_install_kubectx

- name:
  ansible.builtin.include_tasks: helm.yaml
  when: kubectl_install_helm

- name: Copy bashrc config
  ansible.builtin.template:
    src: kubectl.bash.j2
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/kubectl.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
