---
- name: Install go
  community.general.snap:
    name: go
    state: present
    classic: true
  become: true

- name: Copy bashrc config
  ansible.builtin.copy:
    src: "go.bash"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/go.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
