---
- name: Install tfenv | Remove previous installation
  ansible.builtin.file:
    path: "{{ tfenv_path }}"
    state: absent
  become: true

- name: Install tfenv | Download required version
  ansible.builtin.git:
    repo: "{{ tfenv_repo }}"
    version: "{{ tfenv_version }}"
    dest: "{{ tfenv_path }}"
    depth: 1
  become: true

- name: Install tfenv | Link to /usr/local/bin/tfenv
  ansible.builtin.file:
    path: /usr/local/bin/tfenv
    src: "{{ tfenv_path }}/bin/tfenv"
    state: link
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Install tfenv | Link to /usr/local/bin/terraform
  ansible.builtin.file:
    path: /usr/local/bin/terraform
    src: "{{ tfenv_path }}/bin/terraform"
    state: link
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true
