---
- name: Get tfenv current version
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      tfenv --version | cut -d' ' -f2
  register: tfenv_current_version
  changed_when: false
  failed_when: false

- name: Install tfenv
  ansible.builtin.include_tasks: install_tfenv.yaml
  when: |
    tfenv_current_version is failed or
    tfenv_current_version.stdout != tfenv_version

- name: Install Terraform versions.
  ansible.builtin.command: tfenv install "{{ item }}"
  become: true
  loop: "{{ terraform_versions }}"

- name: Use Terraform verison.
  ansible.builtin.command: tfenv use "{{ terraform_use_version }}"
  become: true
