---
- name: Check if sshaws is installed
  ansible.builtin.stat:
    path: "{{ sshaws_installation_path }}/sshaws"
  register: sshaws

- name: Download binary
  ansible.builtin.get_url:
    url: "https://github.com/uritau/sshaws/releases/latest/download/sshaws"
    dest: "{{ sshaws_installation_path }}/sshaws"
    owner: "{{ caller_user.stdout }}"
    group: "{{ caller_group.stdout }}"
    mode: u=rwx,g=rx,o=rx
  when: not sshaws.stat.exists
