---
- name: Install docker snap.
  community.general.snap:
    name: docker
  become: true

- name: Create docker group.
  ansible.builtin.group:
    name: docker
    state: present
    system: true
  become: true

- name: Add user to docker group.
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
    state: present
  become: true

- name: Copy .bashrc config
  ansible.builtin.copy:
    src: "docker.bash"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/docker.bash"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: u=rw,g=r,o=r
