---
- name: Install docker snap.
  community.general.snap:
    name: docker

- name: Create docker group.
  ansible.builtin.group:
    name: docker
    state: present
    system: true
  become: true

- name: Add user to docker group.
  ansible.builtin.user:
    name: '{{ caller_user.stdout }}'
    groups: docker
    append: true
    state: present
  become: true
